version: "0.2"
ignorePaths:
  - .git
  - .gitignore
dictionaryDefinitions: []
dictionaries: []
words:
  - anthropics
  - bluemonday
  - coverprofile
  - DB_DBNAME
  - DBTX
  - GOARCH
  - healthcheck
  - isready
  - ldflags
  - mydb
  - pkgs
  - sqlc
